project_name: gotosocial-thumbnailer
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/thesuess/gotosocial-thumbnailer:{{ .Version }}-amd64"
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/goreleaser/gotosocial-thumbnailer
      - --label=org.opencontainers.image.source=https://github.com/theSuess/gotosocial-thumbnailer
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=BSD0
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "ghcr.io/thesuess/gotosocial-thumbnailer:{{ .Version }}-arm64"
    build_flag_templates:
      - --platform=linux/arm64/v8
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/goreleaser/gotosocial-thumbnailer
      - --label=org.opencontainers.image.source=https://github.com/theSuess/gotosocial-thumbnailer
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=BSD0
docker_manifests:
  - name_template: ghcr.io/thesuess/gotosocial-thumbnailer:{{ .Version }}
    image_templates:
      - "ghcr.io/thesuess/gotosocial-thumbnailer:{{ .Version }}-amd64"
      - "ghcr.io/thesuess/gotosocial-thumbnailer:{{ .Version }}-arm64"
